export const cristinBio = "Cristin is an all-around creative person with a deep-rooted passion for dogs… especially bird dogs. She has been training, observing, and loving dogs since childhood. In addition to client dogs, she has personally owned and trained a wide variety of breeds, including: Yorkshire Terriers, Shetland Sheepdogs, Schnauzers, Collies, Labrador Retrievers, Chesapeake Bay Retrievers, Weimaraners, and German Shorthaired Pointers. She combines this lifetime of hands-on experiences with a dog psychology methodology to develop a solid and reliable process for getting the most out of your dog. Since 2010 she has been providing in-home behavior modification services where her unique ability to identify problem sources and devise applicable solutions delivers proven results. Originally from Maryland, waterfowling and labs were in her blood. But her interest in versatile hunting dog training was piqued in 2014 when she brought home a German Shorthaired Pointer named Remmel and joined NAVHDA. A busy mom with two boys and (at least) four active GSPs, she not only understands the importance of a well-balanced life, but also recognizes the positive impact it can have on your relationship with your dog. Regardless of your situation, she promises to work with you to find the best solutions that work for you and your dog, both in the field and at home. Cristin is also an accomplished artist whose favorite subjects include dogs, waterfowl, and upland birds. She is currently the Director of Testing for the Keystone Chapter of NAVHDA. When not working with dogs, she enjoys hunting, fishing, crabbing, and just about anything outdoors."
export const brandtBio = "Brandt is a detail-oriented person with a background in engineering, construction, and excavation. He’s a busy dad with two girls, a licensed SEO, a PSMA Certified Inspector, and he can finesse earth with heavy equipment like an artist forming clay. An avid hunter, Brandt always dreamed of having a farm of his own with enough land to hunt and a dog of his own to hunt alongside him. His bird dog journey began in 2013 when he brought home a German Shorthaired Pointer named Molson. He didn’t really know what he wanted out of his dog at that time, only that he didn’t want a female. With 4 sisters, 2 daughters, and 7 nieces Brandt knew the new addition to the family needed to be male. Although predominantly a deer hunter, Brandt quickly recognized his dog needed more. After joining NAVHDA to help him get the most for Molson, he realized he not only enjoyed the versatile hunting dog training process, but he had a real knack for helping others through issues with their bird dogs. He has a developed a keen eye for seeing things that occur in the field that most handlers overlook. This allows him to provide effective solutions to seemingly difficult problems. Brandt has been the Director of Training for the Keystone Chapter of NAVHDA since 2016 and has helped countless members train their versatile dogs. He has qualified for the NAVHDA Invitational three times, is in the NAVHDA Apprentice Judge Program, and is currently training a dog for the NAVHDA Utility Test. When not training in the field, Brandt enjoys hunting, fishing, and cooking. He encourages everyone he meets to try new things."

export const dogBios = {
    molson: 'Our "long-tailed shorthair" is a true gentleman in the house, but a phenom in the field. He has a nose like no other dog and hops effortlessly through the field like a gazelle.',
    remmel: 'Our solid-liver "brown dog," is big and powerful and highly successful in the field. He’s a self-taught therapy dog for Cristin. He nearly died from a splenic torsion, but is back better than ever.',
    camo: 'Our "block head," is a powerhouse in a compact body. Prefering work over affection, this dog always gets it done in the field. He has thick coat and loves the cold…and he has an intense point.',
    modelo: 'Our "little stinker," who not only causes a lot of shenanigans but also has the most adorable skunk stripe on the underside of her tail. She’s an up-and-comer and already showing tremendous potential.',
}
